### ISSUE TITLE
Unable to update Radarr

### ISSUE THREAD

**Issue by Puppetmaster91** [evilmarty/hassio-addons#47]
Hi,

I am unable to update Radarr add-on on home assistant OS 2023.10.0(and .1).
I am not sure if it is Home assistant 2023.10.0 that causes the issue or something in the radarr docker container, hopefully you are able to cast some light on it.

you can see log below.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:13:12 (1 occurrences)
Last logged: 11:13:12

[140048354095168] Error updating Radarr: Can't install ghcr.io/evilmarty/hassio-radarr:5.0.3.8127-ls190: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=5.0.3.8127-ls190&fromImage=ghcr.io%2Fevilmarty%2Fhassio-radarr&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/evilmarty/hassio-radarr:5.0.3.8127-ls190: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=5.0.3.8127-ls190&fromImage=ghcr.io%2Fevilmarty%2Fhassio-radarr&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Radarr: Can't install ghcr.io/evilmarty/hassio-radarr:5.0.3.8127-ls190: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=5.0.3.8127-ls190&fromImage=ghcr.io%2Fevilmarty%2Fhassio-radarr&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

```

**Comment by evilmarty** [comment]
Hi @Puppetmaster91. I've fixed the issue, which was due to a failing test that halted the container being built by the workflow but somehow still updated the config with the new version. I'll have to look into that issue when I have more time.
