### ISSUE TITLE
Unable to update Sonarr

### ISSUE THREAD

**Issue by Puppetmaster91** [evilmarty/hassio-addons#55]
Hi

I have the same issue as of my issue created oct 9. 2023 for Radarr, but now it is Sonarr :)

I am unable to update Sonarr add-on on home assistant OS 2023.12.4

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 08:14:53 (1 occurrences)
Last logged: 08:14:53

[140068097625024] Error updating Sonarr: Can't install ghcr.io/evilmarty/hassio-sonarr:4.0.0.748-ls220: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.0.0.748-ls220&fromImage=ghcr.io%2Fevilmarty%2Fhassio-sonarr&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/evilmarty/hassio-sonarr:4.0.0.748-ls220: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.0.0.748-ls220&fromImage=ghcr.io%2Fevilmarty%2Fhassio-sonarr&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Sonarr: Can't install ghcr.io/evilmarty/hassio-sonarr:4.0.0.748-ls220: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.0.0.748-ls220&fromImage=ghcr.io%2Fevilmarty%2Fhassio-sonarr&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
```

**Comment by evilmarty** [comment]
Hi. Thanks for informing me. I am aware that the update is broken, this is due to a change with the upstream container that's breaking tests thus the auto-update workflow is unable to build the new image. When I have time I will fix the issue.

**Comment by evilmarty** [comment]
This has been fixed. Special thanks to @nkm8 who began the work. Apologies this took a while, the timing was not good for me due to school holiday period.
